sudo: required
services:
  - docker

before_install:
  - docker pull node:16 # Use a Docker image with Node.js v16
  - docker run -d -v $(pwd):/app -w /app node:16 npm install # Install dependencies inside the container

script:
  - docker run --rm -v $(pwd):/app -w /app node:16 npm run test --watch=false --browsers=ChromeHeadless
