language: node_js
node_js:
  - 16
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @angular/cli
install:
  - npm ci
script:
  - ng test --watch=false --browsers=ChromeHeadless
