language: node_js
node_js:
  - 18.19

before_install:
  - npm install -g @angular/cli@17.3 # Install Angular CLI version 17.3

install:
  - npm ci # Use clean install

script:
  - ng test --watch=false --browsers=ChromeHeadless
