language: node_js
node_js:
  - lts/* # Use the latest LTS version of Node.js

cache:
  directories:
    - node_modules

before_install:
  - npm install -g @angular/cli # Ensure Angular CLI is installed

install:
  - npm ci # Clean install dependencies

script:
  - ng test --watch=false --browsers=ChromeHeadless # Run tests in headless mode
