language: node_js
node_js:
  - 18.19 # You can also use a specific version like 18.19
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @angular/cli
install:
  - npm ci
script:
  - ng test --watch=false --browsers=ChromeHeadless
