language: node_js
os: linux
dist: focal # Try using Focal (Ubuntu 20.04) or bionic (Ubuntu 18.04)

node_js:
  - 18.19 # Set Node.js version to 18.19

before_install:
  - npm install -g @angular/cli@17.3 # Install Angular CLI version 17.3 globally

install:
  - npm ci # Clean install of dependencies

script:
  - ng test --watch=false --browsers=ChromeHeadless # Run tests in headless mode
