language: node_js
os: linux
dist: bionic # Use Bionic (Ubuntu 18.04) or focal (Ubuntu 20.04)

node_js:
  - 18.19 # Node.js version 18.19

before_install:
  - npm install -g @angular/cli@17.3 # Install Angular CLI version 17.3 globally

install:
  - npm ci # Clean install of dependencies

script:
  - ng test --watch=false --browsers=ChromeHeadless # Run tests in headless mode
