sudo: required
services:
  - docker

before_install:
  - docker pull node:18.19 # Use a Docker image with Node.js v18
  - docker run -d -v $(pwd):/app -w /app node:18.19 npm install # Install dependencies inside the container
  - docker run -v $(pwd):/app -w /app node:18.19 npm install @angular/cli # Install Angular CLI locally

script:
  - docker run --rm -v $(pwd):/app -w /app node:18.19 npm run test --watch=false --browsers=ChromeHeadless # Run tests
